#!/bin/bash

alias clip="xclip -selection clipboard"

clipfile() {
  cat $1 | xclip -selection clipboard -i
}

git-sync() {
  (git checkout main || \
  git checkout master) && \
  git pull upstream master && \
  git push origin master
 }
